// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test1
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HarpoonString = "3324b810-3638-4d86-9a10-635e784a75e7";
        public static Guid Harpoon = new Guid(HarpoonString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AppendTab = 0x0100;
        public const int DeleteTab = 0x0101;
        public const int OverwriteTab0 = 0x0102;
        public const int OverwriteTab1 = 0x0105;
        public const int OverwriteTab2 = 0x0106;
        public const int OverwriteTab3 = 0x0107;
        public const int OverwriteTab4 = 0x0108;
        public const int OverwriteTab5 = 0x0109;
        public const int OverwriteTab6 = 0x0110;
        public const int OverwriteTab7 = 0x0111;
        public const int OverwriteTab8 = 0x0112;
        public const int OverwriteTab9 = 0x0113;
        public const int NextTab = 0x0114;
        public const int PrevTab = 0x0115;
        public const int SwitchToTab0 = 0x0116;
        public const int SwitchToTab1 = 0x0117;
        public const int SwitchToTab2 = 0x0118;
        public const int SwitchToTab3 = 0x0119;
        public const int SwitchToTab4 = 0x0120;
        public const int SwitchToTab5 = 0x0121;
        public const int SwitchToTab6 = 0x0122;
        public const int SwitchToTab7 = 0x0123;
        public const int SwitchToTab8 = 0x0124;
        public const int SwitchToTab9 = 0x0125;
        public const int HarpoonToolWindow = 0x0126;
        public const int SwapLeft = 0x0127;
        public const int SwapRight = 0x0128;
        public const int ClearAll = 0x0129;
        public const int GotoFirst = 0x0130;
        public const int GotoLast = 0x0131;
        public const int SaveCurrentSession = 0x0132;
        public const int ScoochIndexes = 0x0133;
        public const int SaveAllSessions = 0x0134;
        public const int ScrollHalfPageDown = 0x0135;
        public const int ScrollHalfPageUp = 0x0136;
        public const int ShowTabOnSlnTree = 0x0137;
    }
}